config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  devise_for :users
  root "contacts#index"
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string
#  email      :string
#  phone      :string
#  address    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Contact < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  roles                  :string
#

class User < ActiveRecord::Base
  ################################################################################ 
  ## PeterGate Roles
  ## The :user role is added by default and shouldn't be included in this list.
  petergate(roles: [:admin])
  ################################################################################
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts, -> { order 'name' }, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /contacts
  def index
    @contacts = current_user.contacts.paginate(page: params[:page], per_page: 10)
  end

  # GET /contacts/1
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: 'Contact was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contact_params
      params.require(:contact).permit(:user_id, :name, :email, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field.form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .field.form-group
    = f.label :phone
    = f.text_field :phone, class: "form-control"
  .field.form-group
    = f.label :address
    = f.text_area :address, class: "form-control"
  .actions = f.submit

app/views/contacts/edit.html.slim
h1 Edit

== render 'form'

= link_to 'Show', @contact
'|
= link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1 Contacts

table.table.table-striped
  thead
    tr
      th Name
      th Email
      th Phone
      th Address
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = link_to contact.name, contact
        td = contact.email
        td = contact.phone
        td = contact.address
        td = link_to contact, data: {:confirm => 'Are you sure?'}, :method => :delete do
          i.fa.fa-times-circle

= link_to new_contact_path, class: "btn btn-primary"
  i.fa.fa-user-plus New Contact

br

= will_paginate @contacts

app/views/contacts/new.html.slim
h1 New Contact

== render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.slim
p#notice = notice

h1 Contact

table.table.table-striped

  thead 
    tr
      th 
      th 

  tbody
    tr
      td 
        strong Name:
      td = @contact.name
    tr
      td
        strong Email:
      td = @contact.email
    tr
      td 
        strong Phone:
      td = @contact.phone
    tr
      td
        strong Address:
      td = @contact.address
  
= link_to 'Edit', edit_contact_path(@contact)
'|
= link_to 'Back', contacts_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title AddressBook
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 

  body
    #main_container.fluid-container
      #header.navbar-header
        = link_to "My Address Book", root_path, :class => 'navbar-brand'
        - if user_signed_in?
          ul.navbar-nav.nav.navbar-right
            li
              = link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' 
            li
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
        - else
          ul.navbar-nav.nav.navbar-right
            li
              = link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' 
            li
              = link_to "Login", new_user_session_path, :class => 'navbar-link'
      
     

      .row
        #main_content.col-sm-12.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3
          p.notice 
            = notice
          p.alert
            = alert

          = yield 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>